os: linux
jdk: oraclejdk8
dist: trusty
sudo: true
group: stable
language: java
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
install:
  - ./scripts/travis.build.sh
  - ./mvnw -e clean install -DskipTests=true -Dmaven.javadoc.skip=true -Dspring-boot.run.profiles=dev
  - ./mvnw -e clean install -DskipTests=true -Dmaven.javadoc.skip=true -Dspring-boot:run.prifiles=prod
