os: linux
jdk: oraclejdk8
dist: trusty
sudo: true
group: stable

install:
  - ./mvnw -e clean install -DskipTests=true -Dmaven.javadoc.skip=true -Dspring-boot.run.profiles=dev
  - ./mvnw -e clean install -DskipTests=true -Dmaven.javadoc.skip=true -Dspring-boot:run.prifiles=prod
language: java
services:
  - mysql
before_script:
  - ./scripts/travis.build.sh
