os: linux
jdk: oraclejdk8
dist: trusty
sudo: true
group: stable
language: java
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
script:
  - chmod +x ./scripts/travisci.build.sh
  - ./scripts/travisci.build.sh